/* gl.c -- https://github.com/takeiteasy/fungl
  
  This file was generated by https://github.com/takeiteasy/fungl/blob/master/tools/gl.rb

  fungl puts the fun back into OpenGL
  
  Copyright (C) 2024  George Watson

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <https://www.gnu.org/licenses/>. */

#include "gl.h"
#include <stdlib.h>

#define X(T, N) T __##N = (T)((void*)0);
#if FUNGL_VERSION >= GL_VERSION_1_0
GL_FUNCTIONS_1_0
#endif
#if FUNGL_VERSION >= GL_VERSION_1_1
GL_FUNCTIONS_1_1
#endif
#if FUNGL_VERSION >= GL_VERSION_1_2
GL_FUNCTIONS_1_2
#endif
#if FUNGL_VERSION >= GL_VERSION_1_3
GL_FUNCTIONS_1_3
#endif
#if FUNGL_VERSION >= GL_VERSION_1_4
GL_FUNCTIONS_1_4
#endif
#if FUNGL_VERSION >= GL_VERSION_1_5
GL_FUNCTIONS_1_5
#endif
#if FUNGL_VERSION >= GL_VERSION_2_0
GL_FUNCTIONS_2_0
#endif
#if FUNGL_VERSION >= GL_VERSION_2_1
GL_FUNCTIONS_2_1
#endif
#if FUNGL_VERSION >= GL_VERSION_3_0
GL_FUNCTIONS_3_0
#endif
#if FUNGL_VERSION >= GL_VERSION_3_1
GL_FUNCTIONS_3_1
#endif
#if FUNGL_VERSION >= GL_VERSION_3_2
GL_FUNCTIONS_3_2
#endif
#if FUNGL_VERSION >= GL_VERSION_3_3
GL_FUNCTIONS_3_3
#endif
#if FUNGL_VERSION >= GL_VERSION_4_0
GL_FUNCTIONS_4_0
#endif
#if FUNGL_VERSION >= GL_VERSION_4_1
GL_FUNCTIONS_4_1
#endif
#if FUNGL_VERSION >= GL_VERSION_4_2
GL_FUNCTIONS_4_2
#endif
#if FUNGL_VERSION >= GL_VERSION_4_3
GL_FUNCTIONS_4_3
#endif
#if FUNGL_VERSION >= GL_VERSION_4_4
GL_FUNCTIONS_4_4
#endif
#if FUNGL_VERSION >= GL_VERSION_4_5
GL_FUNCTIONS_4_5
#endif
#if FUNGL_VERSION >= GL_VERSION_4_6
GL_FUNCTIONS_4_6
#endif
#undef X

#if !defined(NULL)
#define NULL ((void*)0)
#endif

#if defined(FUNGL_WINDOWS) || defined(__CYGWIN__)
#ifndef _WINDOWS_
#undef APIENTRY
#endif
#include <windows.h>
typedef void* (APIENTRYP PFNWGLGETPROCADDRESSPROC_PRIVATE)(const char*);
static PFNWGLGETPROCADDRESSPROC_PRIVATE glLoaderGetProcAddressPtr;
static HMODULE libGL = NULL;

#ifdef _MSC_VER
#ifdef __has_include
#if __has_include(<winapifamily.h>)
#define HAVE_WINAPIFAMILY 1
#endif
#elif _MSC_VER >= 1700 && !_USING_V110_SDK71_
#define HAVE_WINAPIFAMILY 1
#endif
#endif

#ifdef HAVE_WINAPIFAMILY
#include <winapifamily.h>
#if !WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP) && WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP)
#define IS_UWP 1
#endif
#endif

static int LoadGLLibrary(void) {
#ifndef IS_UWP
    if ((libGL = LoadLibraryW(L"opengl32.dll"))) {
        void(*tmp)(void);
        tmp = (void(*)(void)) GetProcAddress(libGL, "wglGetProcAddress");
        glLoaderGetProcAddressPtr = (PFNWGLGETPROCADDRESSPROC_PRIVATE)tmp;
        return glLoaderGetProcAddressPtr != NULL;
    }
#endif
    return 0;
}

static void CloseGLLibrary(void) {
    if (libGL) {
        FreeLibrary((HMODULE)libGL);
        libGL = NULL;
    }
}
#else
#include <dlfcn.h>
#if !defined(FUNGL_MAC) && !defined(__HAIKU__)
typedef void* (APIENTRYP PFNGLXGETPROCADDRESSPROC_PRIVATE)(const char*);
static PFNGLXGETPROCADDRESSPROC_PRIVATE glLoaderGetProcAddressPtr;
#endif
static void* libGL = NULL;

static int LoadGLLibrary(void) {
#if defined(FUNGL_MAC)
    static const char *NAMES[] = {
        "../Frameworks/OpenGL.framework/OpenGL",
        "/Library/Frameworks/OpenGL.framework/OpenGL",
        "/System/Library/Frameworks/OpenGL.framework/OpenGL",
        "/System/Library/Frameworks/OpenGL.framework/Versions/Current/OpenGL"
    };
#else
    static const char *NAMES[] = {"libGL.so.1", "libGL.so"};
#endif

    unsigned int index = 0;
    for (index = 0; index < (sizeof(NAMES) / sizeof(NAMES[0])); index++) {
        if ((libGL = dlopen(NAMES[index], RTLD_NOW | RTLD_GLOBAL))) {
#if defined(FUNGL_MAC) || defined(__HAIKU__)
            return 1;
#else
            glLoaderGetProcAddressPtr = (PFNGLXGETPROCADDRESSPROC_PRIVATE)dlsym(libGL,
                "glXGetProcAddressARB");
            return glLoaderGetProcAddressPtr != NULL;
#endif
        }
    }
    return 0;
}

static void CloseGLLibrary(void) {
    if (libGL) {
        dlclose(libGL);
        libGL = NULL;
    }
}
#endif

static void* LoadGLProc(const char *namez) {
    void* result = NULL;
    if (libGL == NULL)
        return NULL;

#if !defined(FUNGL_MAC) && !defined(__HAIKU__)
    if (glLoaderGetProcAddressPtr)
        result = glLoaderGetProcAddressPtr(namez);
#endif
    if (!result) {
#if defined(FUNGL_WINDOWS) || defined(__CYGWIN__)
        result = (void*)GetProcAddress((HMODULE)libGL, namez);
#else
        result = dlsym(libGL, namez);
#endif
    }

    return result;
}

#define X(T, N) \
    if (!(__##N = (T)LoadGLProc(#N))) \
        failures++;

int glInit(void) {
    int failures = 0;
    if (LoadGLLibrary()) {
#if FUNGL_VERSION >= GL_VERSION_1_0
GL_FUNCTIONS_1_0
#endif
#if FUNGL_VERSION >= GL_VERSION_1_1
GL_FUNCTIONS_1_1
#endif
#if FUNGL_VERSION >= GL_VERSION_1_2
GL_FUNCTIONS_1_2
#endif
#if FUNGL_VERSION >= GL_VERSION_1_3
GL_FUNCTIONS_1_3
#endif
#if FUNGL_VERSION >= GL_VERSION_1_4
GL_FUNCTIONS_1_4
#endif
#if FUNGL_VERSION >= GL_VERSION_1_5
GL_FUNCTIONS_1_5
#endif
#if FUNGL_VERSION >= GL_VERSION_2_0
GL_FUNCTIONS_2_0
#endif
#if FUNGL_VERSION >= GL_VERSION_2_1
GL_FUNCTIONS_2_1
#endif
#if FUNGL_VERSION >= GL_VERSION_3_0
GL_FUNCTIONS_3_0
#endif
#if FUNGL_VERSION >= GL_VERSION_3_1
GL_FUNCTIONS_3_1
#endif
#if FUNGL_VERSION >= GL_VERSION_3_2
GL_FUNCTIONS_3_2
#endif
#if FUNGL_VERSION >= GL_VERSION_3_3
GL_FUNCTIONS_3_3
#endif
#if FUNGL_VERSION >= GL_VERSION_4_0
GL_FUNCTIONS_4_0
#endif
#if FUNGL_VERSION >= GL_VERSION_4_1
GL_FUNCTIONS_4_1
#endif
#if FUNGL_VERSION >= GL_VERSION_4_2
GL_FUNCTIONS_4_2
#endif
#if FUNGL_VERSION >= GL_VERSION_4_3
GL_FUNCTIONS_4_3
#endif
#if FUNGL_VERSION >= GL_VERSION_4_4
GL_FUNCTIONS_4_4
#endif
#if FUNGL_VERSION >= GL_VERSION_4_5
GL_FUNCTIONS_4_5
#endif
#if FUNGL_VERSION >= GL_VERSION_4_6
GL_FUNCTIONS_4_6
#endif
        CloseGLLibrary();
    }
    return failures;
}
#undef X
